### ISSUE TITLE
Can't expand to detail view

### ISSUE THREAD

**Issue by Fedolodic** [rviscomi/capo.js#15]
Hey! Just wanted to mention that this tool is awesome!
Although I am having one issue with expanding the visual output from the script into a detailed view.

I ran the script on the citi.com website and this is what I see:

<img width="1502" alt="Screenshot 2023-05-30 at 11 12 23 AM" src="https://github.com/rviscomi/capo.js/assets/12787345/b869842c-760d-4653-8728-a47acb65b005">

**Comment by rviscomi** [comment]
Hi @Fedolodic thanks for the kind words!

It looks like citi.com is blocking the `console.log` function in production, so there's nothing in the group to expand.

```js
"PROD" == this._appConfigService.getEnvironment() && (console.log = function() {
  return !1
}
);
```

You could restore the function using a trick [like this](https://stackoverflow.com/a/7089553/1022333) before running the capo script:

```js
var i = document.createElement('iframe');
i.style.display = 'none';
document.body.appendChild(i);
window.console = i.contentWindow.console;
```

<img width="1116" alt="image" src="https://github.com/rviscomi/capo.js/assets/1120896/cc67f868-f53a-4ad5-add4-d147a502116e">

Since this is site-specific I don't think there are any changes needed to the script itself.
